name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore
        run: dotnet restore DevPod.Provider.ACI.sln

      - name: Build
        run: dotnet build --no-restore --configuration Release DevPod.Provider.ACI.sln

      - name: Test (with coverage gate)
        run: |
          dotnet test --no-build --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=lcov \
            /p:ExcludeByFile="**/Program.cs" \
            /p:Threshold=70 \
            /p:ThresholdType=line \
            /p:ThresholdStat=total

      - name: Upload Test Results (artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/**

      - name: Upload Coverage (artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            **/coverage.info
